/* autogenerated by Processing revision 1313 on 2026-06-09 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.sound.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class GooseGame extends PApplet {



//================ GLOBAL ==============================
Game game;
PImage bgImg;
SoundFile gameSound;

//=====================================================

//loads the game window loads the files
public void setup() {
  /* size commented out by preprocessor */;
  textSize(32);

  bgImg = loadImage("img1.jpg");
  bgImg.resize(width, height);

  gameSound = new SoundFile(this, "GameSound.wav");
  gameSound.amp(0.02f);

  game = new Game(); // creates new instace of the game.
}

//updates all the graphics that is seen in the game window.
public void draw() {
  background(bgImg);
  game.update();
  game.display();
}

//================ INPUT ==============================

// listens for all inputs from user
public void keyPressed() {
  if (!gameSound.isPlaying()) gameSound.loop(); // BGM will start on 1st key press
  game.keyPressed(key, keyCode);
}

public void keyReleased() {
  game.keyReleased(keyCode);
}

public void mousePressed() {
  game.mousePressed();
}

//=====================================================
//===================== GAME ==========================
//=====================================================

class Game {

  int state = 0; // 0=start, 1=playing, 2=game over
  int score = 0;
  int countdownTime = 10;
  int startTime;

  Goose goose;
  Star star;

  Game() {
    goose = new Goose();
    star = new Star();
  }

  public void start() {
    state = 1;
    startTime = millis();
    score = 0;

    goose.reset();
    star.spawn();
  }

  public void update() {

    if (state == 0) return;

    if (state == 1) {

      int elapsed = (millis() - startTime) / 1000;
      if (elapsed >= countdownTime) {
        state = 2;
        gameSound.stop(); // stop music on game over
      }

      goose.update();
      star.update();

      if (star.checkCollision(goose)) {
        score++;
        star.spawn();
      }
    }
  }

  public void display() {

    if (state == 0) {
      drawStartScreen();
      return;
    }

    int remainingTime = countdownTime - (millis() - startTime)/1000;
    if (remainingTime < 0) remainingTime = 0;

    drawTimer(remainingTime);

    if (state == 1) {
      drawScore();
      goose.display();
      star.display();
    }

    if (state == 2) {
      drawGameOver();
    }
  }

  //================ UI ======================

  public void drawStartScreen() {
    textAlign(CENTER, CENTER);

    fill(0);
    textSize(60);
    text("GOOSE GAME", width/2, height/2 - 120);

    textSize(30);
    text("Collect as many stars as you can!", width/2, height/2 - 80);

    textSize(28);
    text("Controls:", width/2, height/2 - 40);
    text("← → Move", width/2, height/2);
    text("↓ Move Down", width/2, height/2 + 40);
    text("SPACE Flap", width/2, height/2 + 80);

    textSize(26);
    fill(200);
    text("Press any key to start", width/2, height/2 + 160);
  }

  public void drawScore() {
    textAlign(LEFT, TOP);
    fill(255);
    textSize(30);
    text("Score: " + score, 20, 20);
  }

  public void drawTimer(int t) {
    fill(255, 0, 0);
    textAlign(RIGHT, TOP);
    textSize(40);
    text(t, width - 20, 20);
  }

  public void drawGameOver() {
    textAlign(CENTER, CENTER);

    fill(255);
    textSize(60);
    text("TIMES UP", width/2, height/2 - 40);

    textSize(50);
    text("Score: " + score, width/2, height/2 + 20);

    textSize(24);
    fill(0);
    text("Click to restart", width/2, height/2 + 80);
  }

  //================ CONTROLS ======================

  public void keyPressed(char k, int code) {

    if (state == 0) {
      start();
      return;
    }

    if (state != 1) return;

    if (code == LEFT) goose.moveLeft(true);
    if (code == RIGHT) goose.moveRight(true);
    if (code == DOWN) goose.moveDown(true);
    if (k == ' ') goose.flap();
  }

  public void keyReleased(int code) {
    if (code == LEFT) goose.moveLeft(false);
    if (code == RIGHT) goose.moveRight(false);
    if (code == DOWN) goose.moveDown(false);
  }

  public void mousePressed() {
    if (state == 2) {
      start();
    }
  }
}

//=====================================================
//===================== GOOSE =========================
//=====================================================

class Goose {

  float x = 0, y = 0;
  float w = 100, h = 110;

  float moveSpeed = 6;
  float floatSpeed = 0.15f;
  float flapPower = -5;
  float gravity = -2;

  boolean facingRight = false;

  boolean left, right, down;

  PImage[] frames;
  int currentFrame = 0;
  int frameCounter = 0;
  int frameDelay = 5;

  Goose() {
    frames = new PImage[9];

    for (int i = 0; i < frames.length; i++) {
      frames[i] = loadImage("flap" + i + ".png");
      frames[i].resize((int)w, (int)h);
    }
  }

  public void update() {

    if (left) {
      x -= moveSpeed;
      facingRight = false; 
    }
    if (right) {
      x += moveSpeed;
      facingRight = true;
    }
    if (down) y += moveSpeed;

    gravity += floatSpeed;
    y += gravity;

    animate();
    constrainPosition();
  }

  public void flap() {
    gravity = flapPower;
  }

  public void animate() {
    frameCounter++;
    if (frameCounter >= frameDelay) {
      currentFrame = (currentFrame + 1) % frames.length;
      frameCounter = 0;
    }
  }

  public void display() {
    pushMatrix();
    translate(x + w/2, y + h/2);
    scale(facingRight ? -1 : 1, 1);
    imageMode(CENTER);
    image(frames[currentFrame], 0, 0, w, h);
    popMatrix();
  }

  public void constrainPosition() {
    x = constrain(x, 0, width - w);
    y = constrain(y, 0, height - h);
  }

  public void moveLeft(boolean b) { left = b; }
  public void moveRight(boolean b) { right = b; }
  public void moveDown(boolean b) { down = b; }

  public void reset() {
    x = 0;
    y = 0;
    gravity = -2;
    currentFrame = 0;
  }
}

//=====================================================
//===================== STAR ==========================
//=====================================================

class Star {

  float x, y;
  float size = 25;

  PImage[] frames;
  int frameIndex = 0;
  int animSpeed = 6;

  Star() {
    frames = new PImage[6];
    for (int i = 0; i < 6; i++) {
      frames[i] = loadImage("star" + (i+1) + ".png");
      frames[i].resize((int)size, 0);
    }
  }

  public void spawn() {
    x = random(50, width-50);
    y = random(50, height-100);
    frameIndex = 0;
  }

  public void update() {
    if (frameCount % animSpeed == 0) {
      frameIndex = (frameIndex + 1) % frames.length;
    }
  }

  public void display() {
    imageMode(CENTER);
    image(frames[frameIndex], x, y);
  }

  public boolean checkCollision(Goose g) {
    float d = dist(x, y, g.x + g.w/2, g.y + g.h/2);
    return d < size/2 + g.w/2;
  }
}


  public void settings() { size(800, 600); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "GooseGame" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
